### ISSUE TITLE
modify this plugin for more options

### ISSUE THREAD

**Issue by CyberShot** [syamilmj/Aqua-Verifier#1]
I have this issue where I support more than one marketplace. How hard would it be to add a field to this plugin that not only accepts themeforest username but also any other username along with a provided code for registration? so lets say I am selling my template on mojo-themes. You don't want to have two support forums. Could this be done?

**Comment by syamilmj** [comment]
Do mojo-themes have api for checking purchases?

**Comment by CyberShot** [comment]
They are working on one

Jamie.

Sent from my cell phone.

----- Reply message -----

**Comment by syamilmj** [comment]
How do you check for purchases now?

**Comment by CyberShot** [comment]
We don't. But I can quiz someone who is suspected of buying and if the pass the test I could give them a code that you hard wire into the plugin that will allow them access to the forums. Maybe you add q splash page to the login? Themeforest users sign in here, all others click this link and that let's them choose a username and enter the pass code supplied by me

Jamie.

Sent from my cell phone.

----- Reply message -----

**Comment by syamilmj** [comment]
I think it'd be more practical if you can just add the user manually through admin panel, instead of going through the trouble to generate custom codes, splash page etc.

Until mojo-themes actually have an API that can automate this process, I'm afraid I don't think it would be a necessity.

Sorry if my answer somehow do not meet your expectation.

Cheers

**Comment by CyberShot** [comment]
Your answer is fine. I didn't consider adding them manually. That could work out just fine.
